7
# Zeng Weilei
# tom 20circuit XXX XXX in shor'scode
# are There three versions of thiscircuit 1>standard one 2>simplified one 3>more simplified
# shows Here 1>the standard one

h 6
c 0 6
c 1 6
c 2 6
c 3 6
c 4 6
c 5 6
h 6
m 0 6

#For the last part in this file, manually change the classical bit for saving measurement result. (following example in conv5v5v2.qc). The sequence is also writen in conv5.txt. conv7 use the same sequence.
